name: CI/CD Pipeline

on:
  push:
    branches:
      - anton     # This workflow will only run on pushes to the 'devel' branch
      - matt
      - Michael
  pull_request:
    branches:
      - anton     # This workflow will only run on pull requests targeting the 'devel' branch
      - matt
      - Michael

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Or 'adopt', 'oracle', etc.
          cache: 'gradle' # Caches Gradle dependencies

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # Ensures the Gradle wrapper is executable

      - name: Build with Gradle
        run: ./gradlew build # Executes the Gradle build command

      - name: Test with Gradle
        run: ./gradlew test      # Executes the Gradle test command